Importing Numpy Library

In [2]:
import numpy as np

````
Creating a Matrix with Numpy
````

In [3]:
matrix_1 = np.array([[2,3],[6,7]])
print(matrix_1)

[[2 3]
 [6 7]]


In [4]:
matrix_1.shape

(2, 2)

In [5]:
matrix_2 = np.array([[10,35,45],[50,64,80],[20,15,90]])
print(matrix_2)

[[10 35 45]
 [50 64 80]
 [20 15 90]]


In [6]:
matrix_2.shape

(3, 3)

```
Creating Matrices with  Random Values
```

In [7]:
random_matrix = np.random.rand(3,3)
print(random_matrix)

[[0.98406525 0.33289671 0.500243  ]
 [0.18588615 0.99112123 0.8841189 ]
 [0.71766209 0.86167745 0.97063899]]


In [8]:
# Creating Matrices with  Random Integers

random_integer_matrix = np.random.randint(100, size=(3,3))
print(random_integer_matrix)

[[40 44 63]
 [ 8  9 52]
 [12  5 76]]


```
Matrix with all values as 1
```

In [9]:
matrix_3 = np.ones((4,4))
print(matrix_3)
# float point values

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [10]:
# integer values
matrix_3 = np.ones((4,4),dtype=int)
print(matrix_3)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


```
 Null Matrix --> Matrix with all values as 0
```

In [11]:
# integer values
null_matrix = np.zeros((4,4),dtype=int)
print(null_matrix)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [12]:
# floating point values
null_matrix = np.zeros((4,4))
print(null_matrix)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


```
Identity Matrix --> All diagonal values are 1
```

In [13]:
# integer values
identity_matrix = np.eye(5,5, dtype=int)
print(identity_matrix)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [14]:
# float point values
identity_matrix = np.eye(5,5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


```
Transpose of a Matrix
```

In [15]:
# Matrix with random integer values
a = np.random.randint(100, size=(4,5))
print(a)

[[61 68 93 18 45]
 [54  7 89 27 79]
 [ 7 92 59 73 11]
 [ 2 84 75 84 60]]


In [16]:
transpose_of_a = np.transpose(a)
print(transpose_of_a)

[[61 54  7  2]
 [68  7 92 84]
 [93 89 59 75]
 [18 27 73 84]
 [45 79 11 60]]


```
Matrix Addition --> Two Matrices can be added only if they have the same shape
```

In [17]:
# creating two matrices
A = np.array([[2,3],[4,5]])
B = np.array([[5,3],[6,1]])

In [18]:
print(A)

[[2 3]
 [4 5]]


In [19]:
print(B)

[[5 3]
 [6 1]]


In [20]:
A.shape

(2, 2)

In [21]:
B.shape

(2, 2)

In [22]:
sum = A + B
print(sum)

[[ 7  6]
 [10  6]]


In [23]:
# addition of  random int matrices of size 3 x 3

matrix_1 = np.random.randint(10, size =(3,3))
matrix_2 = np.random.randint(20, size=(3,3))

In [24]:
print(matrix_1)

[[3 1 3]
 [3 6 6]
 [7 0 9]]


In [25]:
print(matrix_2)

[[16 11 18]
 [17  6 10]
 [ 4  0 19]]


In [26]:
sum = np.add(matrix_1,matrix_2)   ## or sum = matrix_1 + matrix_2
print(sum)

[[19 12 21]
 [20 12 16]
 [11  0 28]]


```
Matrix subtraction --> Two Matrices can be subtracted only if they have the same shape
```

In [27]:
# subtraction of  random int matrices of size 3 x 3

matrix_1 = np.random.randint(10, size =(3,3))
matrix_2 = np.random.randint(20, size=(3,3))

In [28]:
print(matrix_1)

[[1 3 6]
 [2 0 4]
 [5 9 8]]


In [29]:
print(matrix_2)

[[ 1  7 19]
 [ 5  1  7]
 [13 16  2]]


In [30]:
difference = np.subtract(matrix_2,matrix_1)
print(difference)

[[ 0  4 13]
 [ 3  1  3]
 [ 8  7 -6]]


```
Multiplying a Matrix by a Scalar
```


In [33]:
x = 5
y = np.random.randint(10,size=(4,4))
print(y)

[[8 9 0 5]
 [1 1 3 2]
 [7 8 6 8]
 [2 8 9 7]]


In [37]:
product = np.multiply(x,y)  # product = x * y
print(product)

[[40 45  0 25]
 [ 5  5 15 10]
 [35 40 30 40]
 [10 40 45 35]]


```
Multiplying 2 Matrices
```

In [38]:
matrix_1 = np.random.randint(5, size =(3,3))
matrix_2 = np.random.randint(5, size=(3,3))

In [39]:
print(matrix_1)

[[4 1 2]
 [2 2 3]
 [1 4 3]]


In [40]:
print(matrix_2)

[[3 2 2]
 [0 4 0]
 [0 1 1]]


In [43]:
product = np.dot(matrix_1,matrix_2)
print(product)

[[12 14 10]
 [ 6 15  7]
 [ 3 21  5]]


```
Element wise Matrix Multiplication -->Both Matrices should have same shape.
```

In [44]:
matrix_3 = np.random.randint(5, size =(3,3))
matrix_4 = np.random.randint(5, size=(3,3))

In [45]:
print(matrix_3)

[[2 0 4]
 [3 2 0]
 [1 4 1]]


In [46]:
print(matrix_4)

[[0 3 1]
 [3 3 3]
 [1 3 2]]


In [48]:
product = np.multiply(matrix_3,matrix_4)
print(product)

[[ 0  0  4]
 [ 9  6  0]
 [ 1 12  2]]
