 Tensors are Multi Dimensional Arrays


An array is an ordered arrangement of numbers

In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
tensor_one_d = tf.constant([2,4,6,8,10])
print(tensor_one_d)

tf.Tensor([ 2  4  6  8 10], shape=(5,), dtype=int32)


In [ ]:
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,-1],
    [1,5,6],
    [2,3,8]
])
print(tensor_two_d)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


In [ ]:
tensor_three_d = tf.constant([
    [[1,2,0],
    [3,5,1]],

    [[10,2,0],
    [1,0,2]],

    [[5,8,0],
    [2,7,0]],

   [[2,1,9],
   [4,-3,32]],])
print(tensor_three_d)
print(tensor_three_d.ndim)

tf.Tensor(
[[[ 1  2  0]
  [ 3  5  1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(4, 2, 3), dtype=int32)
3


In [ ]:
tensor_four_d = tf.constant([
    [  #first block
    [[1,2,0],[3,5,1]],
    [[10,2,0],[1,0,2]],
    [[5,8,0],[2,7,0]],
   [[2,1,9],[4,-3,32]],
     ],
    [  #second block
    [[32,8,0],[3,5,9]],
    [[10,2,0],[1,0,2]],
    [[5,8,0],[2,7,0]],
    [[2,1,9],[4,-3,32]]
    ],
    [   # Third block
    [[1,2,0],[3,5,1]],
    [[10,2,0],[1,0,2]],
    [[5,8,0],[2,7,0]],
    [[2,1,9],[4,-3,32]]
    ]
])
print(tensor_four_d)
print(tensor_four_d.ndim)

tf.Tensor(
[[[[ 1  2  0]
   [ 3  5  1]]

  [[10  2  0]
   [ 1  0  2]]

  [[ 5  8  0]
   [ 2  7  0]]

  [[ 2  1  9]
   [ 4 -3 32]]]


 [[[32  8  0]
   [ 3  5  9]]

  [[10  2  0]
   [ 1  0  2]]

  [[ 5  8  0]
   [ 2  7  0]]

  [[ 2  1  9]
   [ 4 -3 32]]]


 [[[ 1  2  0]
   [ 3  5  1]]

  [[10  2  0]
   [ 1  0  2]]

  [[ 5  8  0]
   [ 2  7  0]]

  [[ 2  1  9]
   [ 4 -3 32]]]], shape=(3, 4, 2, 3), dtype=int32)
4


In [ ]:
tensor_str= tf.constant(['hello world!','hi'])
print(tensor_str)

tf.Tensor([b'hello world!' b'hi'], shape=(2,), dtype=string)


In [ ]:
import numpy as np

In [ ]:
np_array = np.array([2,4,6,8])
print(np_array)

[2 4 6 8]


In [ ]:
convereted_tensor = tf.convert_to_tensor(np_array)
print(convereted_tensor)

tf.Tensor([2 4 6 8], shape=(4,), dtype=int64)


In [ ]:
# identity matrix
eye_tenor = tf.eye(
    num_rows=3,
    num_columns=5,
    batch_shape=[2,],
    dtype=tf.dtypes.float32,
    name = None
    )
print(eye_tenor.shape)
print(eye_tenor)

(2, 3, 5)
tf.Tensor(
[[[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]]

 [[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]]], shape=(2, 3, 5), dtype=float32)


In [ ]:
#fill tenso r -  fills all the values with desired scalar

fill_tensor = tf.fill([3,2,4],9)
print(fill_tensor)

tf.Tensor(
[[[9 9 9 9]
  [9 9 9 9]]

 [[9 9 9 9]
  [9 9 9 9]]

 [[9 9 9 9]
  [9 9 9 9]]], shape=(3, 2, 4), dtype=int32)


In [ ]:
# ones tensor
ones_tensor = tf.ones([3,2,1])
print(ones_tensor)


tf.Tensor(
[[[1.]
  [1.]]

 [[1.]
  [1.]]

 [[1.]
  [1.]]], shape=(3, 2, 1), dtype=float32)


In [ ]:
# oneslike  tensor -  creates a tensor of all ones with shape as same as the input
ones_like_tensor = tf.ones_like(fill_tensor)
print(ones_like_tensor)

tf.Tensor(
[[[1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]]], shape=(3, 2, 4), dtype=int32)


In [ ]:
# zeros tensor - creates a tensor with all elements set to zero
zeros_tensor = tf.zeros([3,2,5])
print(zeros_tensor)


tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(3, 2, 5), dtype=float32)


In [ ]:
# shape - returns  shape of tensor
print(tf.shape(zeros_tensor))

tf.Tensor([3 2 5], shape=(3,), dtype=int32)


In [ ]:
# rank - retuns rank of tensor(no of indices required to uniquely select each element)
t = tf.constant([[1,1,1],[2,2,2],[3,3,3],[4,4,4],[5,5,5]])
tf.rank(t)
# size = returns size of tensor(total no of values in tensor)
tf.size(t)

<tf.Tensor: shape=(), dtype=int32, numpy=15>

In [ ]:
# random.normal - random values from normal distribution
random_tensor = tf.random.normal([2,2],mean=10)
print(random_tensor)

tf.Tensor(
[[10.386326  8.500119]
 [11.256667 10.499942]], shape=(2, 2), dtype=float32)


In [ ]:
# random uniform - random values from uniform distribution
random_tensor_uniform = tf.random.uniform([5,5],minval=2,maxval=20,dtype=tf.dtypes.int32)
print(random_tensor_uniform)

tf.Tensor(
[[ 9 15  7 12  7]
 [13 14 18 11 15]
 [ 8 12  9  7 19]
 [14 11 17 18  7]
 [19 11 18 17 18]], shape=(5, 5), dtype=int32)


In [ ]:
tf.random.set_seed(5)
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32, seed=10))

tf.random.set_seed(5)
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32, seed=10))

tf.Tensor([4 3 1], shape=(3,), dtype=int32)
tf.Tensor([4 3 2], shape=(3,), dtype=int32)
tf.Tensor([4 3 1], shape=(3,), dtype=int32)
tf.Tensor([4 3 2], shape=(3,), dtype=int32)


In [ ]:
tf.random.set_seed(5)
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32, seed=10))

tf.random.set_seed(5)
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32, seed=10))

tf.Tensor([4 3 1], shape=(3,), dtype=int32)
tf.Tensor([4 3 2], shape=(3,), dtype=int32)
tf.Tensor([4 3 1], shape=(3,), dtype=int32)
tf.Tensor([4 3 2], shape=(3,), dtype=int32)


In [ ]:
# Indexing a tensor
tensor_indexed = tf.constant([[2,4,6,8],
                            [10,12,14,16],
                             [18,20,22,24]])
#                             0 1 2 3 4 5 6 7
print(tensor_indexed[0,0:4])#row 1
print(tensor_indexed[0:2]) #row 1 :row2
print(tensor_indexed[:2,1:3])#elements (4,6
                                      #12,14)

tf.Tensor([2 4 6 8], shape=(4,), dtype=int32)
tf.Tensor(
[[ 2  4  6  8]
 [10 12 14 16]], shape=(2, 4), dtype=int32)
tf.Tensor(
[[ 4  6]
 [12 14]], shape=(2, 2), dtype=int32)


In [ ]:
#3d tensor indexing
tensor_indexed_3d = tf.constant(
    [[[1,2,0],
      [3,5,-1]],  #1st block(0)

     [[10,2,0],
      [1,0,2]],  #2nd bloxk(1)

     [[5,8,0],
      [2,7,6]],   #3rd bloick(2)

     [[2,1,9],
      [4,-3,2]]  #4th block -> (3), [1st row -> 0], [(3rd element) 2nd coloumn-> 2]
      ])

print(tensor_indexed_3d.shape)

(4, 2, 3)


In [ ]:
# slice value of element 9 in the 4th block

tensor_indexed_3d = tf.constant(
    [[[1,2,0],
      [3,5,-1]],  #1st block(0)

     [[10,2,0],
      [1,0,2]],  #2nd bloxk(1)

     [[5,8,0],
      [2,7,6]],   #3rd bloick(2)

     [[2,1,9],
      [4,-3,2]]  #4th block -> (3), [1st row -> 0], [(3rd element) 2nd coloumn-> 2]
      ])

print(tensor_indexed_3d[3,0,2])
print(tensor_indexed_3d[3,0])   # row elements - >[2,1,9]
print(tensor_indexed_3d[3,0:2,0:2])   # row elements - >[2,1,4,-3]


tf.Tensor(9, shape=(), dtype=int32)
tf.Tensor([2 1 9], shape=(3,), dtype=int32)
tf.Tensor(
[[ 2  1]
 [ 4 -3]], shape=(2, 2), dtype=int32)
